schema: "http://heddo.local/graphql"
documents: "./graphql/*.{gql,graphql}"
extensions:
  codegen:
    generates:
      ./graphql/generated/schema.ts:
        plugins:
          - "typescript"
          - "typescript-operations"
          - "typescript-generic-sdk"
      ./graphql.schema.json:
        plugins:
        - "introspection"
