fragment ConfigPageSettingsFields on ConfigPagesSettings {
  header:fieldDefaultHeader {
    entity{
      ...on MediaImage{
        image:fieldMediaImage {
          url,
          height,
          width,
          alt
        }
      }
    }
  }
}
