query ConfigPage($type: String!) {
  configPagesQuery(
    filter: { conditions: { operator: EQUAL, field: "type", value: [$type] } }
  ) {
    entities {
      entityLabel
      # Fields fragments depending on ConfigPage type
      ...ConfigPageSettingsFields

    }
  }
}
