query Paths {
  nodeQuery(filter: {conditions:[{field: "status", value: "1"}]}) {
    entities {
      entityLabel
      entityType
      entityBundle
      entityUrl {
        path
        routed
      }
    }
  }
}
