query Paths {
    nodeQuery(limit: 100, filter: {conditions:[{field: "status", value: "1"}]}) {
      entities {
        entityLabel
        entityType
        entityBundle
        entityUrl {
          path
          routed
        }
      }
    }
}
