import Layout from '@/components/Layout'
import { getPaths } from '@/libs/api'
import { getGlobalData } from '@/libs/global'
import { getPageData, PageContext } from '@/libs/page'
import { GetStaticPaths, GetStaticProps } from 'next'
import Head from 'next/head'

const Page = ({ page }) => {

  return (
    <Layout page={page}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </Layout>
  )
}

export const getStaticPaths: GetStaticPaths = async () => {
  const paths = await getPaths()

  return {
    paths,
    fallback: false,
  }
}

export const getStaticProps: GetStaticProps = async (context: PageContext) => {
  const [page, global] = await Promise.all([getPageData(context), getGlobalData(context)])

  return {
    props: {
      page,
      global,
    }
  }
}

export default Page
