import Layout from '@/components/Layout'
import { getPaths } from '@/lib/utils'
import { getPageData, PageContext } from '@/lib/page'
import { GetStaticPaths, GetStaticProps } from 'next'
import Head from 'next/head'



const Page = ({ node }) => {
  return (
    <Layout node={node}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </Layout>
  )
}

export const getStaticPaths: GetStaticPaths = async () => {
  const paths = await getPaths()

  return {
    paths,
    fallback: false,
  }
}

export const getStaticProps: GetStaticProps = async (context: PageContext) => {
  const {node, global} = await getPageData(context, "page")

  return {
    props: {
      node,
      global
    }
  }
}

export default Page
